### ISSUE TITLE
segfault when crashing with smoke against palm tree in Mayan Mayhem

### ISSUE THREAD

**Issue by madebr** [dethrace-labs/dethrace#132] opened 2022-06-03 00:38 UTC
When crashing against a palm tree with a smoking (=broken) car in Mayan Mayhem (first map of Carmageddon Splat Pack), the game segfaults.

The following stack trace is print:
```
0: SmokeLine at /home/maarten/programming/dethrace/src/DETHRACE/common/spark.c:846
1: SmokeCircle at /home/maarten/programming/dethrace/src/DETHRACE/common/spark.c:949
2: SmokeCircle3D at /home/maarten/programming/dethrace/src/DETHRACE/common/spark.c:1084
3: DrawTheGlow at /home/maarten/programming/dethrace/src/DETHRACE/common/spark.c:1837 (discriminator 2)
4: RenderSmoke at /home/maarten/programming/dethrace/src/DETHRACE/common/spark.c:1176
5: RenderAFrame at /home/maarten/programming/dethrace/src/DETHRACE/common/graphics.c:1620 (discriminator 2)
6: MainGameLoop at /home/maarten/programming/dethrace/src/DETHRACE/common/mainloop.c:596
7: DoRace at /home/maarten/programming/dethrace/src/DETHRACE/common/mainloop.c:722
8: DoGame at /home/maarten/programming/dethrace/src/DETHRACE/common/structur.c:538
9: DoProgram at /home/maarten/programming/dethrace/src/DETHRACE/common/structur.c:646
10: GameMain at /home/maarten/programming/dethrace/src/DETHRACE/common/main.c:106
11: original_main at /home/maarten/programming/dethrace/src/DETHRACE/pc-dos/dossys.c:666
12: main at /home/maarten/programming/dethrace/src/DETHRACE/main.c:29
13: ?? ??:0
```

**How to reproduce**
- Start DethRace with `DETHRACE_ROOT_DIR` pointing to a splat pack directory
- Start a new game, select *Max Damage*, any difficulty, and start the *Mayan Mayhem* race
- When in-race, Enter `IBETYOUCANTPRINTCUNT` for entering the edit mode
- Press `F4` until you enter "damage edit mode"
- Make speed (but not too much to not trigger #131), drive a bit around in the grass and crash against a palm tree. Before you crash, make sure you have a damaged car that generates smoke. Use the the keys `0`-`6` (combined with `SHIFT`) for that.

**Comment by dethrace-labs** [comment] 2023-02-20 09:20
Do you still see this on the latest version if you remove the `return` at the top of `DrawTheGlow`? I used to be able to reproduce this but now I cannot. Maybe it is somehow fixed? 😂

**Comment by madebr** [comment] 2023-02-20 23:36
No I cannot reproduce it anymore. Let's be bold and re-enable it. :rofl:

**Comment by zear** [comment] 2023-02-22 10:26
Re-opening this issue.

I just had a crash with similar backtrace on the current `main` (48b70bb8ff08dae10b00d285a9cc6e6b24a1eeac), while driving around in "Fragged at the Factory" near the start position. Whatever triggered the crash, must have happened off-screen by one of the opponent cars.

```
Stack trace:
0: SmokeLine at /home/zear/projects/dethrace/src/DETHRACE/common/spark.c:876
1: SmokeCircle at /home/zear/projects/dethrace/src/DETHRACE/common/spark.c:980
2: SmokeCircle3D at /home/zear/projects/dethrace/src/DETHRACE/common/spark.c:1115
3: DrawTheGlow at /home/zear/projects/dethrace/src/DETHRACE/common/spark.c:1938 (discriminator 2)
4: RenderSmoke at /home/zear/projects/dethrace/src/DETHRACE/common/spark.c:1219
5: RenderAFrame at /home/zear/projects/dethrace/src/DETHRACE/common/graphics.c:1684 (discriminator 2)
6: MainGameLoop at /home/zear/projects/dethrace/src/DETHRACE/common/mainloop.c:596
7: DoRace at /home/zear/projects/dethrace/src/DETHRACE/common/mainloop.c:726
8: DoGame at /home/zear/projects/dethrace/src/DETHRACE/common/structur.c:540
9: DoProgram at /home/zear/projects/dethrace/src/DETHRACE/common/structur.c:648
10: GameMain at /home/zear/projects/dethrace/src/DETHRACE/common/main.c:106
11: original_main at /home/zear/projects/dethrace/src/DETHRACE/pc-dos/dossys.c:675
12: main at /home/zear/projects/dethrace/src/DETHRACE/main.c:33
13: ?? ??:0
14: ?? ??:0
```

**Comment by zear** [comment] 2023-02-23 12:26
The issue is because in:
https://github.com/dethrace-labs/dethrace/blob/48b70bb8ff08dae10b00d285a9cc6e6b24a1eeac/src/DETHRACE/common/spark.c#L876
...the `(shade_offset_int - r_squared * r_multiplier_int) >> 8` operation is performed on a signed integer, and is thus subject to sign extend.
I don't think this calculation has ever intended to produce negative values, as it is used as an index to an array.
Turning this into `(uint32_t)(shade_offset_int - r_squared * r_multiplier_int) >> 8` mitigates the crash, but I will yet need to understand if that's the intended OG behavior.

**Comment by zear** [comment] 2023-02-25 14:16
@madebr, @dethrace-labs 

Ok, this is a nasty one:
https://github.com/dethrace-labs/dethrace/blob/48b70bb8ff08dae10b00d285a9cc6e6b24a1eeac/src/DETHRACE/common/spark.c#L876

1) Whenever `SmokeLine` is called through `DrawTheGlow`, the `shade_offset_int - r_squared * r_multiplier_int` operation results in a **negative** value (`shade_offset_int` is less than `r_squared * r_multiplier_int`).
I haven't observed this case in any other code paths that call `SmokeLine`.

2) Subject to [usual arithmetic conversions](https://en.cppreference.com/w/c/language/conversion#Usual_arithmetic_conversions), the `((shade_offset_int - r_squared * r_multiplier_int) >> 8) & 0xffffff00` operation will cast the left-handed operand of `&` to `unsigned int`, producing **unsigned** type result.

3) Because `*scr_ptr` is also an unsigned type, the array is accessed at a large positive index, instead of the (probably unintended) small negative index.

4) On 32-bit systems, such as DOS and Windows 95, pointer arithmetic on said large array index would overflow, resulting in a memory access that is **equal** to the small negative index, simply grabbing some game data a couple bytes before the start of the shade table.
On 64 bit systems, this large array index access results in **page fault**.

The fix for this is trivial - just cast the index to a signed type to make negative offset access explicit:
```
*scr_ptr = shade_ptr[*scr_ptr + (int)(((shade_offset_int - r_squared * r_multiplier_int) >> 8) & 0xffffff00)];
```

Two questions remain, though:
1) Is this an OG bug? Are the negative index accesses deliberate, or just an overlook? Should we instead cap negative accesses at index 0?

2) Why haven't you guys observed the page fault at your platforms (MacOS and Windows, I presume)? Are you running them in 32-bit compatible mode?

**Comment by dethrace-labs** [comment] 2023-02-26 02:11
Love the detailed debugging and description, thank you! 

I expect that this was a big that was never noticed during development. I think we should cap negative accesses at 0 like you suggest.

to clarify on (2), both @madebr and I have seen it many times, but we haven’t found a consistent repro. I could most commonly repro when looking at the glow on an angle where the glow was near the edge of the screen.

**Comment by zear** [comment] 2023-02-26 12:14
> I could most commonly repro when looking at the glow on an angle where the glow was near the edge of the screen

That's precisely when it happens. I can replicate it 100% times.

Fixed in https://github.com/dethrace-labs/dethrace/pull/295.

**Closed** 2023-02-28 10:08 UTC
